name: Deploy deepRunnerGolang
on:
  push:
    branches: [ main, dev ]
  workflow_dispatch:
defaults:
  run:
    working-directory: ./
jobs:
  dockerize:
    name: dockerize
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.16'
      - name: Install latest npm
        run: npm install -g npm@latest
      - name: build
        run: npm ci && npm run package:build
      - name: Display npm log
        if: ${{ failure() }}
        run: cat /home/runner/.npm/_logs/*-debug.log
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: deepf/golang-docker-isolation-provider
      - name: build docker image and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
          
